debug

diff --git a/.github/workflows/security.yaml b/.github/workflows/security.yaml
--- a/.github/workflows/security.yaml
+++ b/.github/workflows/security.yaml
@@ -63,18 +63,16 @@ jobs:
           docker info
 
           echo "Building the Docker image..."
-          echo "IMAGE_NAME is $IMAGE_NAME"
+          IMAGE_NAME="flask-app"
           docker build -t library/$IMAGE_NAME .
-          docker images | grep "library/$IMAGE_NAME" || { echo "Image build failed"; exit 1; }
+          echo "Verifying if the image was built successfully..."
+          docker images | grep -E "library/$IMAGE_NAME\s+latest" || { echo "Image build failed"; exit 1; }
 
           echo "Logging into Docker Hub..."
           echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
 
-          echo "Verifying Trivy setup..."
-          docker pull aquasec/trivy:0.57.1
-          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock busybox echo "Docker socket accessible"
-
           echo "Running Trivy scan..."
+          docker pull aquasec/trivy:0.57.1
           docker run --rm \
             -v /var/run/docker.sock:/var/run/docker.sock \
             aquasec/trivy:0.57.1 \
