debug

diff --git a/.github/workflows/security.yaml b/.github/workflows/security.yaml
--- a/.github/workflows/security.yaml
+++ b/.github/workflows/security.yaml
@@ -62,11 +62,13 @@ jobs:
           echo "Verifying Docker setup..."
           docker info
 
-          echo "Building the Docker image..."
           IMAGE_NAME="flask-app"
+
+          echo "Building the Docker image..."
           docker build -t library/$IMAGE_NAME .
+
           echo "Verifying if the image was built successfully..."
-          docker images | grep -E "library/$IMAGE_NAME\s+latest" || { echo "Image build failed"; exit 1; }
+          docker inspect --type=image library/$IMAGE_NAME:latest > /dev/null || { echo "Image build failed"; exit 1; }
 
           echo "Logging into Docker Hub..."
           echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
